name: Skaffold Github Action
description: Setup Skaffold and all required dependencies
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  skaffold-version:
    default: 2.3.1
    description: Set Skaffold version
    required: false
  kubectl-version:
    default: 1.29.2
    description: Set Kubectl version
    required: false
  container-structure-test-version:
    default: 1.15.0
    description: Set Container Structure Test version
    required: false
  command:
    default: 'diagnose'
    description: Skaffold command to execute. If no command provided, then skaffold will be installed and print version
    required: false
  concurrency:
    default: ''
    description: Number of concurrently running builds. If equals 0 - will run all builds in parallel
    required: false
  push:
    default: ''
    description: Push the built images to the specified image repository
    required: false
  image:
    default: ''
    description: Choose which artifacts to build. Artifacts with image names that contain the expression will be built only. Default is to build sources for all artifacts
    required: false
  images:
    default: ''
    description: Choose which image tags to test.
    required: false
  cache:
    default: ''
    description: Set to false to disable default caching of artifacts
    required: false
  repository:
    default: ''
    description: Default repository value (overrides global config)
    required: false
  insecure-registries:
    default: ''
    description: Target registries for built images which are not secure
    required: false
  filename:
    default: skaffold.yaml
    description: Path or URL to the Skaffold config file
    required: false
  kubeconfig:
    default: ''
    description: Path to the kubeconfig file to use for CLI requests
    required: false
  kube-context:
    default: ''
    description: Deploy to this Kubernetes context
    required: false
  namespace:
    default: ""
    description: Run deployments in the specified namespace
    required: false
  working-directory:
    default: ''
    description: Set current working directory similar to Github Actions run
    required: false
  profile:
    default: ''
    description: Activate profiles by name (prefixed with `-` to disable a profile)
    required: false
  skip-tests:
    default: ''
    description: Whether to skip the tests after building
    required: false
  verbosity:
    default: 'warning'
    description: Log level - one of [panic fatal error warning info debug trace]
    required: false
  interactive:
    default: ''
    description: Allow user prompts for more information
    required: false
  output:
    default: ''
    description: Format output with go-template
    required: false
  file-output:
    default: ''
    description: Filename to write build images to
    required: false
  tag:
    default: ''
    required: false
    description: The optional custom tag to use for images which overrides the current Tagger configuration
outputs:
  output:
    description: Built image tags
runs:
  using: node20
  main: src/index.js
